parameters:
    applestump_mixpanel.factory.class: Applestump\MixpanelBundle\Services\MixpanelFactory
    applestump_mixpanel.user_reader.class: Applestump\MixpanelBundle\Services\Reader
    applestump_mixpanel.token: #blank to be overriden by extension manager class
    applestump_mixpanel.use_fos: true

services:
    applestump_mixpanel.client:
        class: %applestump_mixpanel.factory.class%
        arguments: [%applestump_mixpanel.token%]

    applestump_mixpanel.user_reader:
        class: %applestump_mixpanel.factory.class%
