language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/http-foundation:${SYMFONY_VERSION}
  - composer require doctrine/common:2.4

script: phpunit ./Tests/Annotations/

notifications:
  email:
    - mattlody@gmail.com